# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/www.invictagym.online
cert = /etc/letsencrypt/live/www.invictagym.online/cert.pem
privkey = /etc/letsencrypt/live/www.invictagym.online/privkey.pem
chain = /etc/letsencrypt/live/www.invictagym.online/chain.pem
fullchain = /etc/letsencrypt/live/www.invictagym.online/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = e942b8f031765ebd5389288b531aea6c
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
