--
-- PostgreSQL database dump
--

\restrict uRzdeXSCTkhdCvnbuuDHho3ba2bJrcTDSHhU2cN5WZkc9mR7SGdaM59RCtbA82G

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ubuntu;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ubuntu;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ubuntu;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO ubuntu;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO ubuntu;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO ubuntu;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ubuntu;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ubuntu;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ubuntu;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ubuntu;

--
-- Name: gym_asistencia; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.gym_asistencia (
    id bigint NOT NULL,
    fecha_hora_entrada timestamp with time zone NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.gym_asistencia OWNER TO ubuntu;

--
-- Name: gym_asistencia_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.gym_asistencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_asistencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_cliente; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.gym_cliente (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    cedula character varying(20) NOT NULL,
    correo character varying(254),
    telefono character varying(20),
    foto_perfil character varying(100)
);


ALTER TABLE public.gym_cliente OWNER TO ubuntu;

--
-- Name: gym_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.gym_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_configuracionsistema; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.gym_configuracionsistema (
    id bigint NOT NULL,
    dias_gracia integer NOT NULL
);


ALTER TABLE public.gym_configuracionsistema OWNER TO ubuntu;

--
-- Name: gym_configuracionsistema_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.gym_configuracionsistema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_configuracionsistema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_pago; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.gym_pago (
    id bigint NOT NULL,
    monto numeric(10,2) NOT NULL,
    metodo_pago character varying(20) NOT NULL,
    fecha_pago date NOT NULL,
    suscripcion_id bigint NOT NULL
);


ALTER TABLE public.gym_pago OWNER TO ubuntu;

--
-- Name: gym_pago_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.gym_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_plan; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.gym_plan (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    duracion_dias integer NOT NULL,
    tarifa numeric(10,2) NOT NULL
);


ALTER TABLE public.gym_plan OWNER TO ubuntu;

--
-- Name: gym_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.gym_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_suscripcion; Type: TABLE; Schema: public; Owner: ubuntu
--

CREATE TABLE public.gym_suscripcion (
    id bigint NOT NULL,
    fecha_inscripcion date NOT NULL,
    fecha_vencimiento date,
    estado character varying(10) NOT NULL,
    cliente_id bigint NOT NULL,
    plan_id bigint NOT NULL
);


ALTER TABLE public.gym_suscripcion OWNER TO ubuntu;

--
-- Name: gym_suscripcion_id_seq; Type: SEQUENCE; Schema: public; Owner: ubuntu
--

ALTER TABLE public.gym_suscripcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_suscripcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add cliente	7	add_cliente
26	Can change cliente	7	change_cliente
27	Can delete cliente	7	delete_cliente
28	Can view cliente	7	view_cliente
29	Can add configuracion sistema	8	add_configuracionsistema
30	Can change configuracion sistema	8	change_configuracionsistema
31	Can delete configuracion sistema	8	delete_configuracionsistema
32	Can view configuracion sistema	8	view_configuracionsistema
33	Can add plan	9	add_plan
34	Can change plan	9	change_plan
35	Can delete plan	9	delete_plan
36	Can view plan	9	view_plan
37	Can add asistencia	10	add_asistencia
38	Can change asistencia	10	change_asistencia
39	Can delete asistencia	10	delete_asistencia
40	Can view asistencia	10	view_asistencia
41	Can add suscripcion	11	add_suscripcion
42	Can change suscripcion	11	change_suscripcion
43	Can delete suscripcion	11	delete_suscripcion
44	Can view suscripcion	11	view_suscripcion
45	Can add pago	12	add_pago
46	Can change pago	12	change_pago
47	Can delete pago	12	delete_pago
48	Can view pago	12	view_pago
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	gym	cliente
8	gym	configuracionsistema
9	gym	plan
10	gym	asistencia
11	gym	suscripcion
12	gym	pago
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-30 16:33:08.840415-04
2	auth	0001_initial	2026-07-30 16:33:08.894997-04
3	admin	0001_initial	2026-07-30 16:33:08.908618-04
4	admin	0002_logentry_remove_auto_add	2026-07-30 16:33:08.91382-04
5	admin	0003_logentry_add_action_flag_choices	2026-07-30 16:33:08.917824-04
6	contenttypes	0002_remove_content_type_name	2026-07-30 16:33:08.926997-04
7	auth	0002_alter_permission_name_max_length	2026-07-30 16:33:08.933804-04
8	auth	0003_alter_user_email_max_length	2026-07-30 16:33:08.939231-04
9	auth	0004_alter_user_username_opts	2026-07-30 16:33:08.945471-04
10	auth	0005_alter_user_last_login_null	2026-07-30 16:33:08.951303-04
11	auth	0006_require_contenttypes_0002	2026-07-30 16:33:08.952721-04
12	auth	0007_alter_validators_add_error_messages	2026-07-30 16:33:08.95675-04
13	auth	0008_alter_user_username_max_length	2026-07-30 16:33:08.964382-04
14	auth	0009_alter_user_last_name_max_length	2026-07-30 16:33:08.969263-04
15	auth	0010_alter_group_name_max_length	2026-07-30 16:33:08.974915-04
16	auth	0011_update_proxy_permissions	2026-07-30 16:33:08.98148-04
17	auth	0012_alter_user_first_name_max_length	2026-07-30 16:33:08.987642-04
18	gym	0001_initial	2026-07-30 16:33:09.021734-04
19	sessions	0001_initial	2026-07-30 16:33:09.030882-04
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: gym_asistencia; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.gym_asistencia (id, fecha_hora_entrada, cliente_id) FROM stdin;
1	2026-07-31 15:01:34.928916-04	3
2	2026-07-31 15:02:32.067171-04	3
8	2026-07-31 15:15:05.033335-04	2
9	2026-07-31 15:21:07.818565-04	3
10	2026-07-31 15:23:20.270471-04	3
12	2026-07-31 15:34:11.643302-04	2
22	2026-07-31 16:04:09.138497-04	6
30	2026-08-03 11:24:26.262779-04	8
31	2026-08-03 14:30:39.933695-04	8
32	2026-08-03 14:48:59.98371-04	8
33	2026-08-03 14:50:15.025886-04	8
34	2026-08-03 14:51:02.934598-04	8
35	2026-08-03 15:15:27.882885-04	8
36	2026-08-03 15:18:34.026974-04	8
37	2026-08-03 15:20:03.544985-04	8
38	2026-08-03 15:25:07.890526-04	8
39	2026-08-03 15:59:11.760395-04	8
40	2026-08-03 16:16:14.75174-04	8
41	2026-08-03 16:17:11.297385-04	8
42	2026-08-03 16:25:18.613744-04	8
43	2026-08-03 16:25:29.561526-04	8
\.


--
-- Data for Name: gym_cliente; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.gym_cliente (id, nombre, cedula, correo, telefono, foto_perfil) FROM stdin;
2	Andrea Santiago	31911738	andrea@gmail.com	04147593647	
3	jesus chirinos	28739992	chiripa@gmail.com	04128852573	clientes/28739992.jpeg
6	raul manique	28038957	raul@gmail.com	0414522365	clientes/28038957.jpeg
7	Jose vielma	26810686	vielmalapara@gmail.com	04120789272	clientes/26810686.jpeg
8	jesus machado	28636652	jesus@gmail.com	04247804472	clientes/28636652_YW2BPXi.jpeg
9	juan mercado	1452	juan@gmail.com	0414785526	
\.


--
-- Data for Name: gym_configuracionsistema; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.gym_configuracionsistema (id, dias_gracia) FROM stdin;
1	0
\.


--
-- Data for Name: gym_pago; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.gym_pago (id, monto, metodo_pago, fecha_pago, suscripcion_id) FROM stdin;
1	20.00	Pago Móvil	2026-07-31	1
2	20.00	Pago Móvil	2026-07-31	2
5	5.00	Pago Móvil	2026-07-31	5
7	5.00	Pago Móvil	2026-07-31	7
8	20.00	Pago Móvil	2026-07-31	8
9	20.00	Pago Móvil	2026-07-31	9
10	50.00	Pago Móvil	2026-08-03	10
11	20.00	Pago Móvil	2026-08-03	9
12	50.00	Pago Móvil	2026-08-03	11
\.


--
-- Data for Name: gym_plan; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.gym_plan (id, nombre, duracion_dias, tarifa) FROM stdin;
1	Plan Regular	30	20.00
2	Plan Trimestral	90	50.00
3	Pase Diario	1	5.00
\.


--
-- Data for Name: gym_suscripcion; Type: TABLE DATA; Schema: public; Owner: ubuntu
--

COPY public.gym_suscripcion (id, fecha_inscripcion, fecha_vencimiento, estado, cliente_id, plan_id) FROM stdin;
1	2026-06-03	2026-07-03	Vencido	2	1
2	2026-11-10	2026-12-10	Activo	3	1
5	2026-07-19	2026-07-20	Vencido	6	3
7	2026-07-31	2026-08-01	Activo	2	3
8	2026-07-31	2026-08-30	Activo	6	1
10	2026-07-20	2026-10-18	Activo	8	2
9	2026-06-10	2026-09-02	Activo	7	1
11	2026-07-14	2026-10-12	Activo	9	2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: gym_asistencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.gym_asistencia_id_seq', 43, true);


--
-- Name: gym_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.gym_cliente_id_seq', 9, true);


--
-- Name: gym_configuracionsistema_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.gym_configuracionsistema_id_seq', 1, false);


--
-- Name: gym_pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.gym_pago_id_seq', 12, true);


--
-- Name: gym_plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.gym_plan_id_seq', 3, true);


--
-- Name: gym_suscripcion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ubuntu
--

SELECT pg_catalog.setval('public.gym_suscripcion_id_seq', 11, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: gym_asistencia gym_asistencia_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_asistencia
    ADD CONSTRAINT gym_asistencia_pkey PRIMARY KEY (id);


--
-- Name: gym_cliente gym_cliente_cedula_key; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_cliente
    ADD CONSTRAINT gym_cliente_cedula_key UNIQUE (cedula);


--
-- Name: gym_cliente gym_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_cliente
    ADD CONSTRAINT gym_cliente_pkey PRIMARY KEY (id);


--
-- Name: gym_configuracionsistema gym_configuracionsistema_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_configuracionsistema
    ADD CONSTRAINT gym_configuracionsistema_pkey PRIMARY KEY (id);


--
-- Name: gym_pago gym_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_pago
    ADD CONSTRAINT gym_pago_pkey PRIMARY KEY (id);


--
-- Name: gym_plan gym_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_plan
    ADD CONSTRAINT gym_plan_pkey PRIMARY KEY (id);


--
-- Name: gym_suscripcion gym_suscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_suscripcion
    ADD CONSTRAINT gym_suscripcion_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: gym_asistencia_cliente_id_d2a38747; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX gym_asistencia_cliente_id_d2a38747 ON public.gym_asistencia USING btree (cliente_id);


--
-- Name: gym_cliente_cedula_9b115dc3_like; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX gym_cliente_cedula_9b115dc3_like ON public.gym_cliente USING btree (cedula varchar_pattern_ops);


--
-- Name: gym_pago_suscripcion_id_0ecc5a9e; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX gym_pago_suscripcion_id_0ecc5a9e ON public.gym_pago USING btree (suscripcion_id);


--
-- Name: gym_suscripcion_cliente_id_b252042e; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX gym_suscripcion_cliente_id_b252042e ON public.gym_suscripcion USING btree (cliente_id);


--
-- Name: gym_suscripcion_plan_id_04604f39; Type: INDEX; Schema: public; Owner: ubuntu
--

CREATE INDEX gym_suscripcion_plan_id_04604f39 ON public.gym_suscripcion USING btree (plan_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gym_asistencia gym_asistencia_cliente_id_d2a38747_fk_gym_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_asistencia
    ADD CONSTRAINT gym_asistencia_cliente_id_d2a38747_fk_gym_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.gym_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gym_pago gym_pago_suscripcion_id_0ecc5a9e_fk_gym_suscripcion_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_pago
    ADD CONSTRAINT gym_pago_suscripcion_id_0ecc5a9e_fk_gym_suscripcion_id FOREIGN KEY (suscripcion_id) REFERENCES public.gym_suscripcion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gym_suscripcion gym_suscripcion_cliente_id_b252042e_fk_gym_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_suscripcion
    ADD CONSTRAINT gym_suscripcion_cliente_id_b252042e_fk_gym_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.gym_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gym_suscripcion gym_suscripcion_plan_id_04604f39_fk_gym_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: ubuntu
--

ALTER TABLE ONLY public.gym_suscripcion
    ADD CONSTRAINT gym_suscripcion_plan_id_04604f39_fk_gym_plan_id FOREIGN KEY (plan_id) REFERENCES public.gym_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict uRzdeXSCTkhdCvnbuuDHho3ba2bJrcTDSHhU2cN5WZkc9mR7SGdaM59RCtbA82G

