# Generated by Django 5.2.16 on 2026-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descriptor_facial',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
