# Generated by Django 5.2.16 on 2026-08-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_cliente_descriptor_facial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='descriptor_facial',
        ),
    ]
