# Generated by Django 5.2.16 on 2026-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_cliente_descriptor_facial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descriptor_facial',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
