# Generated by Django 5.2.16 on 2026-08-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_cliente_descriptor_facial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cargo_especialidad', models.CharField(choices=[('Entrenador', 'Entrenador'), ('Recepcionista', 'Recepcionista'), ('Mantenimiento', 'Mantenimiento'), ('Gerencia', 'Gerencia'), ('Otro', 'Otro')], default='Entrenador', max_length=50)),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], default='Mañana', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
