# Generated by Django 5.2.16 on 2026-08-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gym.personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='descriptor_facial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='personal/'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gym.cliente'),
        ),
    ]
