# Generated by Django 5.2.16 on 2026-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_asistencia_personal_personal_descriptor_facial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cargo_especialidad',
            field=models.CharField(choices=[('Entrenadora', 'Entrenadora'), ('Entrenador', 'Entrenador'), ('Recepcionista', 'Recepcionista'), ('Gerencia', 'Gerencia'), ('Otro', 'Otro')], default='Entrenadora', max_length=50),
        ),
    ]
