# Generated by Django 5.2.16 on 2026-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_personal_cedula_alter_personal_cargo_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de cambio oficial BCV', max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ultima_actualizacion_bcv',
            field=models.DateTimeField(blank=True, help_text='Última vez que se actualizó la tasa', null=True),
        ),
    ]
