# Generated by Django 5.2.16 on 2026-08-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_configuracionsistema_tasa_bcv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField()),
                ('enfoque', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['numero_dia'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=150)),
                ('series', models.CharField(max_length=50)),
                ('repeticiones', models.CharField(max_length=100)),
                ('dia_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='gym.diarutina')),
            ],
        ),
        migrations.CreateModel(
            name='Mesociclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('duracion_semanas', models.IntegerField(default=12)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesociclos', to='gym.personal')),
            ],
        ),
        migrations.AddField(
            model_name='diarutina',
            name='mesociclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='gym.mesociclo'),
        ),
        migrations.CreateModel(
            name='AsignacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gym.cliente')),
                ('mesociclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.mesociclo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProgresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso_levantado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresiones', to='gym.cliente')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='gym.ejerciciorutina')),
            ],
        ),
    ]
