# Generated by Django 5.2.16 on 2026-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_diarutina_ejerciciorutina_mesociclo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarutina',
            options={'ordering': ['semana', 'numero_dia']},
        ),
        migrations.AddField(
            model_name='diarutina',
            name='semana',
            field=models.IntegerField(default=1),
        ),
    ]
