# Generated by Django 5.2.16 on 2026-08-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_diarutina_options_diarutina_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorutina',
            name='peso_asignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
