# Generated by Django 5.2.16 on 2026-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_ejerciciorutina_peso_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncliente',
            name='dias_activos',
            field=models.JSONField(default=list, help_text='Días de la semana seleccionados para entrenar (0=Lunes, 6=Domingo)'),
        ),
    ]
